CRUDCORE/Models/ContactoModel.cs
using System.ComponentModel.DataAnnotations;
namespace CRUDCORE.Models
{
    public class ContactoModel
    {
        public int IdContacto { get; set; }
        [Required(ErrorMessage = "El Campo Es Obligatorio")]
        public string? Nombre { get; set; }
        [Required(ErrorMessage = "El Campo Es Obligatorio")]
        public string? Telefono { get; set; }
        [Required(ErrorMessage = "El Campo Es Obligatorio")]
        public string? Correo { get; set; }
    }
}

CRUDCORE/Models/ErrorViewModel.cs
namespace CRUDCORE.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUDCORE/Controllers/HomeController.cs
using CRUDCORE.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
//ReferenciaLocalization
using Microsoft.AspNetCore.Localization;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Builder;


namespace CRUDCORE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost] 
        //Metodo para cambiar el idioma - Guardarlo 
        public IActionResult EstablecerCultura(string nuevaCultura, string retornarUrl)
        {
            Response.Cookies.Append(
             CookieRequestCultureProvider.DefaultCookieName,
             CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(nuevaCultura)),
             new CookieOptions { Expires = System.DateTimeOffset.UtcNow.AddDays(5) });
            
            return LocalRedirect(retornarUrl);
        }   
    }
}

CRUDCORE/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using CRUDCORE.Datos;
using CRUDCORE.Models;

namespace CRUDCORE.Controllers
{
    public class MantenedorController : Controller
    {

        ContactoDatos _ContactoDatos = new ContactoDatos();

        public IActionResult Listar()
        {//LAVISTAMOSTRARAUNALISTADECONTACTOS
            var oLista = _ContactoDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {///DEVUELVEUNAVISTA

            return View();
        }

        [HttpPost]
        public IActionResult Guardar(ContactoModel oContacto)
        {//RECIBEELOBJETOPARAGUARDARENBD
            if (!ModelState.IsValid)
            {
                return View();
            }
            var respuesta = _ContactoDatos.Guardar(oContacto); 
            if(respuesta)
            
                return RedirectToAction("Listar");
            else
            {
                return View();
            }
            
        }
        public IActionResult Editar(int IdContacto)
        {///DEVUELVEUNAVISTA
            var oContacto = _ContactoDatos.Obtener(IdContacto);
            return View();
        }

        [HttpPost]
        public IActionResult Editar(ContactoModel oContacto)
        {///DEVUELVEUNAVISTA
            if (!ModelState.IsValid)
            {
                return View();
            }
            var respuesta = _ContactoDatos.Editar(oContacto);
            if (respuesta)

                return RedirectToAction("Listar");
            else
            {
                return View();
            }
        }
        public IActionResult Eliminar(int IdContacto)
        {///DEVUELVEUNAVISTA
            var oContacto = _ContactoDatos.Obtener(IdContacto);
            return View();
        }

        [HttpPost]
        public IActionResult Eliminar(ContactoModel oContacto) { 
        ///Hace el cambio
        
            var respuesta = _ContactoDatos.Eliminar(oContacto.IdContacto);
            if (respuesta)

                return RedirectToAction("Listar");
            else
            {
                return View();
            }
        }



    }
}

CRUDCORE/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer verRecurso;

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@verRecurso["textoSaludo"]</h1>
</div>

CRUDCORE/Views/Mantenedor/Editar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer verRecurso;
@model ContactoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        @verRecurso["String1"]
    </div>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            
                <input asp-for="IdContacto" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">@verRecurso["String2"]</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">@verRecurso["String3"]</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">@verRecurso["String4"]</label>
                <input asp-for="Correo" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">@verRecurso["String5"]</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">@verRecurso["String6"]</a>
        </form>
    </div>
</div>

CRUDCORE/Views/Mantenedor/Eliminar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer verRecurso;
@model ContactoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-header">
        @verRecurso["String1"]
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">

            <input asp-for="IdContacto" type="hidden" class="form-control">
            <div class="alert alert-danger" role="alert">
                ¿@verRecurso["String2"] :@Html.DisplayTextFor(model => model.Nombre) ?
            </div>
            <button type="submit" class="btn btn-danger">@verRecurso["String3"]</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">@verRecurso["String4"]</a>
        </form>
    </div>
</div>

CRUDCORE/Views/Mantenedor/Guardar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer verRecurso;

@model ContactoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        @verRecurso["String1"]
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post"> 
            <div class="mb-3">
                <label class="form-label">@verRecurso["String2"]</label>
                <input asp-for="Nombre" type="text" class="form-control" > 
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">@verRecurso["String3"]</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">@verRecurso["String4"]</label>
                <input asp-for="Correo" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">@verRecurso["String5"]</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">@verRecurso["String6"]</a>
        </form>
        </div>
</div>

CRUDCORE/Views/Mantenedor/Listar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer verRecurso;


   @model List<ContactoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-header">
        @verRecurso["String1"]
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">@verRecurso["String2"]<i class="bi bi-plus-circle"></i></a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>@verRecurso["String3"]</th>
                    <th>@verRecurso["String4"]</th>
                    <th>@verRecurso["String5"]</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Correo</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-IdContacto="@item.IdContacto">@verRecurso["String6"]<i class="bi bi-pen"></i></a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-IdContacto="@item.IdContacto">@verRecurso["String7"]<i class="bi bi-trash3"></i></a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

 

CRUDCORE/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer verRecurso;

@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Mvc.Localization;



@inject IOptions<RequestLocalizationOptions> LocalizationOptions;
<!-- Solicitar cultura. -->
@{
    var SolicitarCultura = Context.Features.Get<IRequestCultureFeature>();
    var listaCulturas = LocalizationOptions.Value.SupportedUICultures
    .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName }).ToList();
    <!-- Url Actual-->
    var urlActual = string.IsNullOrEmpty(Context.Request.Path) ? "~/":$"~{Context.Request.Path.Value}{Context.Request.QueryString}"; 
}

    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDCORE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDCORE.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDCORE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@verRecurso["String1"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@verRecurso["String2"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mantenedor" asp-action="Listar">@verRecurso["String3"]</a>
                        </li>
                    </ul>
                    <form class="d-flex" asp-controller="Home" asp-action="EstablecerCultura" asp-route-retornarUrl="@urlActual">
                        
                    <select name="nuevaCultura"
                    asp-for="@SolicitarCultura.RequestCulture.UICulture.Name"
                    asp-items="listaCulturas"
                    onchange="this.form.submit()"
                    >
                        
                        </select>
                    </form>
                </div>
            </div>
        </nav>  
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUDCORE - <a asp-area="" asp-controller="Home" asp-action="Privacy">@verRecurso["String2"]</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>